name: Setup Docker

description: 'Set up Docker to build and push images'

inputs:
  docker-image-name:
    description: 'Docker image name'
    required: true
  commit-sha:
    description: 'Build context for Docker image (default is current directory)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ inputs.commit-sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
          
    - name: Build Docker image
      run: |
        docker build -t ${{ inputs.docker-image-name }}:{{ inputs.commit-sha }} .

    - name: Run Docker Container to Test
      run: |
        docker run --rm  ${{ inputs.docker-image-name }}:${{ inputs.commit-sha }} npm test

    - name: Upload Docker Image as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: ./${{ inputs.docker-image-name }}:${{ inputs.commit-sha }}
