name:  Versioning

outputs:
  version:
    description: "Version"
    value: ${{ steps.set_version.outputs.VERSION }}

runs:
  using: 'composite'
  steps:
    - name: Set up git config
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
      shell: bash

    - name: Get the current version
      run: |
        VERSION=$(git describe --tags --always)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Current Version: $VERSION"
      shell: bash

    - name: Increment version for release (if applicable)
      id: set_version
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "Bumping version"
          # Incrementing the patch version
          VERSION=$(npm version patch --no-git-tag-version)
          echo "New Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
        else
          echo "Skipping version bump"
        fi
      shell: bash

    - name: Commit and tag updated version if version was changed
      if: github.ref == 'refs/heads/main'
      run: |
        git add package.json package-lock.json
        git commit -m "Bump version to ${{ env.VERSION }}"
        git tag -a "${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
        git push && git push --tags
      shell: bash

    - name: Save flag if tag pushed
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
           echo "tag_pushed=true" > tag-info.txt
        else
          echo "tag_pushed=false" > tag-info.txt
        fi
      shell: bash
      
    - name: Upload tag flag artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: tag-flag
        path: tag_flag.txt
