name: CI - Sync Helm Chart Version (Cross Repo)

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  update-helm-chart:
    runs-on: ubuntu-latest
    name: Update version in charts repo

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: tag-flag
        path: ./tag

    - name: Read tag flag
      id: check_tag
      run: |
        TAG_PUSHED=$(cat ./tag/tag-info.txt | grep tag_pushed | cut -d '=' -f2)
        echo "tag_pushed=$TAG_PUSHED" >> $GITHUB_OUTPUT

    - name: Get App Version from Git Tag
      if: steps.check_tag.outputs.tag_pushed == 'true'
      id: get_version
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        APP_VERSION=${TAG_NAME#v}
        echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT

    - name: Clone Helm Charts Repository
      if: steps.check_tag.outputs.tag_pushed == 'true'
      run: |
        # Clone helm repo using access token stored in secret
        git clone https://x-access-token:${{ secrets.HELM_REPO_PAT }}@github.com/kapyuval/msd-test-helm.git
        cd helm-charts-repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update appVersion and image.tag
      if: steps.check_tag.outputs.tag_pushed == 'true'
      run: |
        cd msd-test-helm/charts/msd-test-app

        # Update appVersion in Chart.yaml
        sed -i "s/^appVersion:.*/appVersion: \"${{ steps.get_version.outputs.app_version }}\"/" Chart.yaml

        # Go to where values file is stored
        cd ../../env/dev/msd-test-app
  
        # Update image.tag in values.yaml
        sed -i "s/^\([[:space:]]*tag:\).*/\1 \"${{ steps.get_version.outputs.app_version }}\"/" values.yaml

    - name: Commit and Push Changes
      if: steps.check_tag.outputs.tag_pushed == 'true'
      run: |
        cd msd-test-helm
        git add charts/msd-test-app/Chart.yaml env/dev/msd-test-app/values.yaml
        git commit -m "Bbump chart version to ${{ steps.get_version.outputs.app_version }}"
        git push
