name: CI - Sync Helm Chart Version (Cross Repo)

on:
  workflow_call:
    inputs:
      tag:
        description: 'tag'
        required: true
        type: string
      helm-repo-name:
        required: true
        type: string
jobs:
  update-helm-chart:
    runs-on: ubuntu-latest
    name: Update version in charts repo
    steps:
    - name: Clone Helm Charts Repository
      run: |
        # Clone helm repo using access token stored in secret
        git clone https://x-access-token:${{ secrets.HELM_REPO_PAT }}@github.com/${{ inputs.helm-repo-name }}.git
        REPO_NAME=$(echo "${{ inputs.helm-repo-name }}" | cut -d'/' -f2)
        echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
        cd $REPO_NAME
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update appVersion and image.tag
      run: |
        cd $REPO_NAME/charts/${{ github.event.repository.name }}

        # Update appVersion in Chart.yaml
        sed -i "s/^appVersion:.*/appVersion: \"${{ inputs.tag }}\"/" Chart.yaml

        # Go to where values file is stored
        cd ../../env/dev/${{ github.event.repository.name }}
  
        # Update image.tag in values.yaml
        sed -i "s/^\([[:space:]]*tag:\).*/\1 \"${{ inputs.tag }}\"/" values.yaml

    - name: Commit and Push Changes
      run: |
        cd msd-test-helm
        git add charts/${{ github.event.repository.name }}/Chart.yaml env/dev/${{ github.event.repository.name }}/values.yaml
        git commit -m "Bump chart version to ${{ inputs.tag }}"
        git push
