name: Publish Docker

on:
  workflow_call:
    inputs:
      docker-image-fullname:
        description: 'Docker image name'
        required: true
        type: string
      commit-sha:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Deploy only if it's the main branch
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image tarball
        uses: actions/download-artifact@v4
        with:
          name: msd-test-app-image

      - name: Load Docker image
        run: |
          docker load -i msd-test-app.tar

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker tag msd-test-app:${{ inputs.commit-sha }} ${{ inputs.docker-image-fullname }}:${{ inputs.commit-sha }}
          docker tag msd-test-app:${{ inputs.commit-sha }} ${{ inputs.docker-image-fullname }}:${{ inputs.version }}
          docker tag msd-test-app:${{ inputs.commit-sha }} ${{ inputs.docker-image-fullname }}:latest
          docker push kapyuval/msd-test-app:${{ inputs.commit-sha }}
          docker push kapyuval/msd-test-app:${{ inputs.version }}
          docker push kapyuval/msd-test-app:latest
