name: Setup Docker

on:
  workflow_call:
    inputs:
      docker-image-name:
        description: 'Docker image name'
        required: true
        type: string
      commit-sha:
        required: true
        type: string

jobs:
  build-and-save-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ inputs.commit-sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.docker-image-name }}:${{ inputs.commit-sha }} .

      - name: Save Docker Image to Tar
        run: |
          docker save -o ${{ inputs.docker-image-name }}.tar ${{ inputs.docker-image-name }}:${{ inputs.commit-sha }}

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.docker-image-name }}-image
          path: ${{ inputs.docker-image-name }}.tar
          retention-days: 7
